---
# Install Karaf

- name: Karaf Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Set Facts based on Enviroment
  include: set-facts.yml

- name: Install Karaf
  include: install-karaf.yml

- name: Setup Karaf
  include: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "setup-{{ ansible_distribution }}.yml"
    - "setup-{{ ansible_os_family }}.yml"
