---
# Installs Fedora

- name: Create Fedora Ingest Directory
  file: >-
    path={{ fedora_ingest_directory }} state=directory
    owner={{ tomcat_user }} group={{ tomcat_group }}

- name: Download Fedora
  get_url: >-
    url=https://github.com/fcrepo4-exts/fcrepo-webapp-plus/releases/download/fcrepo-webapp-plus-{{ fedora_version }}/fcrepo-webapp-plus-{{ fedora_version }}.war
    dest={{ download_directory }}/fcrepo-webapp-{{ fedora_version }}.war

- name: Create Fedora Data Directory
  file: >-
    path={{ catalina_base }}/fcrepo4-data state=directory
    owner={{ tomcat_user }} group={{ tomcat_group }} mode=g-w

- name: Deploy Fedora to Tomcat
  command: >-
    cp {{ download_directory }}/fcrepo-webapp-{{ fedora_version }}.war
       {{ catalina_base }}/webapps/fcrepo.war
    creates={{ catalina_base }}/webapps/fcrepo.war
  notify: restart tomcat
  
- name: Fix Fedora Ownership and Permissions
  file: >-
    path={{ catalina_base }}/webapps owner={{ tomcat_user }} group={{ tomcat_group }}

- meta: flush_handlers
