---
__catalina_home: /usr/share/tomcat7
__catalina_base: /var/lib/tomcat7 
__tomcat_user: tomcat7
__tomcat_group: tomcat7
__tomcat_service: tomcat7
__tomcat_java_opts: >-
  -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms2048m -Xmx2048m -XX:NewSize=512m -XX:MaxNewSize=1024m 
  -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile={{ catalina_base }}/webapps/bigdata/WEB-INF/RWStore.properties
__tomcat_required_packages:
  - tomcat7
  - tomcat7-admin
  - haveged # Should help with slow startup
