---
__catalina_home: "{{ ansible_env.CATALINA_HOME }}"
__catalina_base: "{{ ansible_env.CATALINA_HOME }}" 
__tomcat_user: root
__tomcat_group: root
__tomcat_java_opts: >-
  -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms2048m -Xmx2048m -XX:NewSize=256m -XX:MaxNewSize=256m 
  -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile={{ catalina_base }}/webapps/bigdata/WEB-INF/RWStore.properties
  -Djava.security.egd=file:/dev/./urandom
