---
# Common tasks for all hosts

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Set Facts based on Environment
  include: set-facts.yml

- name: Setup Common Dependencies
  include: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "setup-{{ ansible_distribution }}.yml"
    - "setup-{{ ansible_os_family }}.yml"

# Download directory acts as a cache for all later 'get_url' tasks. When using
# Virtualbox this can be made into a synced folder to reduce start-up time.
- name: Create Download Directory
  file: >
    path={{ download_directory }} state=directory
    owner={{ ansible_user | default(lookup('env', 'USER'), true) }}
    group={{ ansible_user | default(lookup('env', 'USER'), true) }}
    mode=a+rwx
