---
- name: Install Additional Software Packages for Development
  apt: name={{ item }} state=present
  with_items:
    - rsync
    - vim
    - emacs
    - htop
    - tree
    - zsh
    - fish

- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
