---
- name: Download Drupal
  shell: >-
    drush dl drupal-{{ drupal_version }} --drupal-project-rename=drupal
    chdir={{ drupal_webserver_document_root }} creates={{ drupal_home }}

- name: Set Perms on Drupal Directory
  file: >-
    path={{ drupal_home }} state=directory
    owner={{ drupal_webserver_user }} group={{ drupal_webserver_group }} mode=ug+rw

- name: Create Drupal Library and Module Folders
  file: >-
    path={{ drupal_home }}/sites/all/{{ item }} state=directory
    owner={{ drupal_webserver_user }} group={{ drupal_webserver_group }} mode=ug+rw
  with_items:
    - libraries
    - modules
    - modules/contrib
    - modules/custom
    - modules/features
